### ISSUE TITLE
plan.htmlの中身を作成

### ISSUE THREAD

**Issue by miyzawa** [rc-project/pr-app-development#19]
今後の活動履歴を書く
書く内容どっかにあるかな？

**Comment by yuu7975** [comment]
![img_1008](https://user-images.githubusercontent.com/23404637/33703707-a0f778ea-db6c-11e7-80af-10f5bebd2147.JPG)

**Comment by yuu7975** [comment]
![img_1010](https://user-images.githubusercontent.com/23404637/33703795-ff29d174-db6c-11e7-820c-65bca851ac7d.JPG)

**Comment by yuu7975** [comment]
![plan_html](https://user-images.githubusercontent.com/23404637/33798630-4e8eb92a-dd5f-11e7-834f-06d68bfcf1ec.PNG)
